<?php

/**
 * Interface to define a Connector, i.e. a class that can 
 * connect to a server and send / receive HTML.
 */
interface Connector {
	/**
	 * Constructor with the URL to connect to.
	 */
	function __construct($url);
	
	/** 
	 * Sets the authentication info.
	 */
	function setLogin($username, $password);
	
	/** 
	 * Sets an array of name / value pairs to be POSTed in the request.
	 */
	function setPostInfo($fields);
	
	/** 
	 * Sets the referer to send in the request.
	 */
	function setReferer($referer);
	
	/** 
	 * Sets the cookie to send in the request.
	 */
	function setCookie($cookie);
	
	/** 
	 * Make a connection to the URL.
	 */
	function connect();
	
	/**
	 * Disconnect from the remote URL.
	 */
	function disconnect();
	
	/**
	 * Retrieve the headers sent as an array of name / value pairs.
	 */
	function getHeaders();
	
	/** 
	 * Retrieve the output generated by the remote URL. If connect() has
	 * not yet been called, this will return NULL.
	 */
	function getOutput();
}

?>